[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d", "Ubuntu"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 48 }

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 11.0

[general]
import = ["themes\\gruvbox_dark.toml"]
working_directory = '\\wsl$\Ubuntu\home\yarden'
